init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --quiet --parallel verify
build:
  project: HDLink.sln
  publish_nuget: true
  verbosity: detailed
test: off
artifacts:
  - path: artifacts\bin\HDLink\$(configuration)\*.nupkg

  